src/database/models.py
from flask import current_app
from werkzeug.security import generate_password_hash, check_password_hash
import jwt
from time import time
from src import db
from src import login_manager
from flask_login import UserMixin


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer(), primary_key=True)
    username = db.Column(db.String(length=30), index=True, unique=True)
    email = db.Column(db.String(length=50), index=True, unique=True)
    password_hash = db.Column(db.String(length=60))

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def get_reset_password_token(self, expires_in=600):
        return jwt.encode(
            {'reset_password': self.id, 'exp': time() + expires_in},
            current_app.config['SECRET_KEY'],
            algorithm='HS256')

    @staticmethod
    def verify_reset_password_token(token):
        try:
            id = jwt.decode(token, current_app.config['SECRET_KEY'],
                            algorithms=['HS256'])['reset_password']
        except:
            return
        return User.query.get(id)


@login_manager.user_loader
def load_user(id):

    return User.query.get(int(id))

class Watchlist(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    movie_id = db.Column(db.Integer(), nullable=False, unique=True)
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id'))

    def __repr__(self):
        return '<User {}>'.format(self.movie_id)

src/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class MovieForm(FlaskForm):
    movie_name = StringField('Enter Movie Name...', validators=[DataRequired()])
    submit = SubmitField(label='Search')

src/__init__.py
import logging
from logging.handlers import SMTPHandler, RotatingFileHandler
import os
from flask_mail import Mail
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_migrate import Migrate
from config import Config

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
bcrypt = Bcrypt(app)
login_manager = LoginManager(app)
login_manager.login_view = "login_page"
login_manager.login_message_category = "info"
mail = Mail()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    db.init_app(app)
    migrate.init_app(app, db)
    ("Migrate was called in create_app")
    login_manager.init_app(app)
    mail.init_app(app)

    from src.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from src.auth import auth as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from src.main import main as main_bp
    app.register_blueprint(main_bp)

    if not app.debug and not app.testing:
        if app.config['MAIL_SERVER']:
            auth = None
            if app.config['MAIL_USERNAME'] or app.config['MAIL_PASSWORD']:
                auth = (app.config['MAIL_USERNAME'],
                        app.config['MAIL_PASSWORD'])
            secure = None
            if app.config['MAIL_USE_TLS']:
                secure = ()
            mail_handler = SMTPHandler(
                mailhost=(app.config['MAIL_SERVER'], app.config['MAIL_PORT']),
                fromaddr='no-reply@' + app.config['MAIL_SERVER'],
                toaddrs=app.config['ADMINS'], subject='Watchmovie Failure',
                credentials=auth, secure=secure)
            mail_handler.setLevel(logging.ERROR)
            app.logger.addHandler(mail_handler)

        if app.config['LOG_TO_STDOUT']:
            stream_handler = logging.StreamHandler()
            stream_handler.setLevel(logging.INFO)
            app.logger.addHandler(stream_handler)
        else:
            if not os.path.exists('logs'):
                os.mkdir('logs')
            file_handler = RotatingFileHandler('logs/watchmovie.log',
                                               maxBytes=10240, backupCount=10)
            file_handler.setFormatter(logging.Formatter(
                '%(asctime)s %(levelname)s: %(message)s '
                '[in %(pathname)s:%(lineno)d]'))
            file_handler.setLevel(logging.INFO)
            app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('Watchmovie startup')

    return app

from src.database import models

src/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from src.main import routes

src/main/routes.py
import os
from src import app
from flask import render_template, flash, redirect, url_for, request, send_from_directory
from flask_login import current_user, login_required
from src import db
from src.main.forms import MovieForm
from src.database.models import Watchlist
from src.main import main
from ml.trained_model import get_suggestions
from get_info import get_info, get_random, get_request
from get_info import get_movie_object, get_movie_info


@main.route('/')
@main.route('/home')
@main.route('/index')
def home():
    return render_template('home.html', title=('Home'))

@main.route('/favicon.ico')
def favicon():
    return send_from_directory(os.path.join(app.root_path, 'static'),
                               'favicon.ico', mimetype='../static/img/favicon.ico')


@main.route('/search', methods=['GET', 'POST'])
@login_required
def search():

    form = MovieForm()
    if form.validate_on_submit():
        title = form.movie_name.data
        if not get_request(title):
            flash('Movie is not in our database, please check correction of the title!', category='alert-danger')
            return redirect(url_for('.search'))
        title = form.movie_name.data
        return redirect(url_for('.result', page_state='movie', title=title))
    suggestions = get_suggestions()
    return render_template('search.html', suggestions=suggestions, form=form)


@main.route("/random", methods=['GET', "POST"])
@login_required
def randomfilm():
    if request.method == "POST":
        return redirect(url_for('.result', page_state='random'))
    return render_template('random.html')

@main.route('/<page_state>/result', methods=['GET', 'POST'])
@login_required
def result(page_state):
    title = request.args.get('title')
    if not title:
        for i in range(0, 10):
            try:
                title, poster, popularity, genres, overview, vote_average, vote_count, release_date, runtime, \
                status, movie_id, casts, cast_details, movie_reviews, movie_cards = get_info(*get_random())
            except Exception:
                print("Error")
            else:
                break
    else:
        title, poster, popularity, genres, overview, vote_average, vote_count, release_date, runtime, \
        status, movie_id, casts, cast_details, movie_reviews, movie_cards = get_info(*get_request(title))
    return render_template('result.html', title=title, overview=overview, poster=poster,
                           popularity=popularity, vote_average=vote_average, vote_count=vote_count,
                           release_date=release_date, runtime=runtime, status=status, genres=genres,
                           movie_cards=movie_cards, movie_id=movie_id,
                           reviews=movie_reviews, casts=casts, cast_details=cast_details, page_state=page_state)



# watchlist
@main.route("/watchlist", methods=["GET"])
@login_required
def watchlist():
    try:
        user_id = int(current_user.get_id())
        films = Watchlist.query.filter_by(user_id=user_id).all()
        films = [get_movie_info(get_movie_object(film.movie_id)) for film in films]
        movie_cards = [(x[0], x[1], round(x[2], 1), x[3], round(x[5], 1), x[10]) for x in films]
        return render_template('watchlist.html', movie_cards=movie_cards)
    except:
        return "", 404



@main.route('/movie/<int:id>', methods=["DELETE"])
@login_required
def delete(movie_id=None):
    try:
        Watchlist.query.filter_by(movie_id=movie_id).delete()
        db.session.commit()
    except:
        return "", 404
    return "", 200


@main.route('/movie/<int:movie_id>', methods=["GET"])
@login_required
def post(movie_id=None):
    # if current_user.is_authenticated():
    user_id = int(current_user.get_id())
    try:
        watch_list = Watchlist(movie_id=movie_id, user_id=user_id)
        db.session.add(watch_list)
        db.session.commit()
    except:
        return {"message": "This film is already added!"}, 409
    return "", 200

src/templates/base.html
<!doctype html>

<html lang="en">
   <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/navbar.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/alerts.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/auth.css') }}">
        <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
          {% block head %}
          {% endblock %}
          <title>
          {% block title %}
          {% endblock %}
         </title>
   </head>
   <body>
   {% include "navbar.html" %}
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
           {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
                  {{ message }}
              </div>
           {% endfor %}
        {% endif %}
      {% endwith %}
      {% block content %}
      {% endblock %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
   	  <script src="https://kit.fontawesome.com/a0043d9bc2.js" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@tarekraafat/autocomplete.js@7.2.0/dist/js/autoComplete.min.js"></script>
        <script src="{{ url_for('static', filename='js/autocomplete.js') }}"></script>
        <script src="{{ url_for('static', filename='js/nav.js') }}"></script>
   </body>
</html>

src/templates/home.html
{% extends 'base.html' %}
{% block title %}
    {{title}}
{% endblock %}
{% block content %}
<body  class="main-img">
<div class="hero-body">
    <div class="column is-auto large-font">
      <p class="title">Watch Movie</p>
      <p class="subtitle">Find new movies to see</p>
      <p class="subtitle">Recommendations for movies</p>
      <p class="subtitle">Film cast</p>
      <p class="subtitle">and IMDB reviews</p>
    </div>
    <div>
        <img src="../static/img/atr.png" style="width:30vw;" alt="lens">
    </div>

  </div>
</body>
{% endblock %}

src/templates/navbar.html
<nav class="navbar navbar-expand-md fixed-top trn navbar-dark">
      <a class="navbar-brand" href="{{ url_for('main.home') }}">
        <img src="/static/img/logo.png" alt="Watch Movies">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
          {% if current_user.is_authenticated %}
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link"  href="{{ url_for('main.search') }}">Find</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"  href="{{ url_for('main.watchlist') }}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"  href="{{ url_for('main.randomfilm') }}">Random</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link">Welcome, {{ current_user.username }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                </li>
            </ul>
          {% else %}
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                </li>
            </ul>
          {% endif %}
      </div>
    </nav>

src/templates/random.html
{% extends 'base.html' %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/recommend.css') }}">
{% endblock %}
{% block title %}
    Welcome to Jim Shaped Coding Market
{% endblock %}
{% block content %}
<body class="collection">

	<div class="d-flex flex-column justify-content-center align-items-center search-block">
    <center><p class="text">Try your luck and get a random movie to see!</p></center>
        <form method="POST">
    <div class="form-group">
      <input class="btn movie-button" type='submit' value="Get random movie">
    </div>
        </form>
	</div>

  <div id="loader" class="text-center">
  </div>
  
  <div class="fail">
    <center><h3>Something go wrong. Please try again!</h3></center>
  </div>

	<div class="results">
    <center>
      <h2 id="name" class="text-uppercase"></h2>
    </center>
	</div>

</body>
{% endblock %}

src/templates/recommend.html
{% extends 'base.html' %}
{% block head %}
  <script src="https://kit.fontawesome.com/a0043d9bc2.js" crossorigin="anonymous"></script>
{% endblock %}
{% block title %}
    Movie
{% endblock %}
{% block content %}
<body id="content">
	<div class="results">
	    <center>
	      <h2 id="name" class="text-uppercase">{{title}}</h2>
	    </center>
	</div>
	<br>

<div id="mycontent">
    <div id="mcontent">
      <div class="poster-lg">
        <img class="poster" style="border-radius: 40px;margin-left: 90px;" height="400" width="250" src={{poster}}>
      </div>
      <div class="poster-sm text-center">
        <img class="poster" style="border-radius: 40px;margin-bottom: 5%;" height="400" width="250" src={{poster}}>
      </div>
      <div id="details">
        <br/>
        <h6 id="title" style="color:white;">TITLE: &nbsp;{{title}}</h6>
        <h6 id="overview" style="color:white;max-width: 40%">OVERVIEW: <br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{overview}}</h6>
        <h6 id="vote_average" style="color:white;">RATING: &nbsp;{{vote_average}}/10 ({{vote_count}} votes)</h6>
        <h6 id="genres" style="color:white;">GENRE: &nbsp;{{genres}}</h6>
        <h6 id="date" style="color:white;">RELEASE DATE: &nbsp;{{release_date}}</h6>
        <h6 id="runtime" style="color:white;">RUNTIME: &nbsp;{{runtime}}</h6>
        <h6 id="status" style="color:white;">STATUS: &nbsp;{{status}}</h6>
      </div>
    </div>
</div>
<br/>





{% for name, details in cast_details.items() if not cast_details.hidden %}
  <div class="modal fade" id="{{details[0]}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel3" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header" style="background-color: #e50914;color: white;">
          <h5 class="modal-title" id="exampleModalLabel3">{{name}}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true" style="color: white">&times;</span>
          </button>
        </div>

        <div class="modal-body">
          <img class="profile-pic" src="{{details[1]}}" alt="{{name}} - profile" style="width: 250px;height:400px;border-radius: 10px;" />
          <div style="margin-left: 20px">
            <p><strong>Birthday:</strong> {{details[2]}} </p>
            <p><strong>Place of Birth:</strong> {{details[3]}} </p>
            <p>
              <p><strong>Biography:</strong><p>
              {{details[4]}}
            </p>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  
  

  {% if casts|length > 1 %}

  <div class="movie-content">
        {% for name, details in casts.items() if not casts.hidden %}
		<div class="swiper-slide" onclick="recommendcard(this)">
          <div class="castcard card" style="width: 15rem;" title="Click to know more about {{name}}" data-toggle="modal" data-target="#{{details[0]}}">
            <div class="imghvr">
              <img class="card-img-top cast-img" id="{{details[0]}}" height="360" width="240" alt="{{name}} - profile" src="{{details[2]}}">
              <figcaption class="fig">
                <button class="card-btn btn btn-danger"> Know More </button>
              </figcaption>
            </div>
            <div class="card-body">
              <h5 class="card-title">{{name|title}}</h5>
              <h5 class="card-title"><span style="color:#756969;font-size: 20px;">Character: {{details[1]|title}}</span></h5>
            </div>
          </div>
		</div>
      {% endfor %}
    </div>
{% endif %}




  <center>
    {% if reviews %}
    <h2 style="color:white">USER REVIEWS</h2>
     <div class="col-md-12" style="margin: 0 auto; margin-top:25px;">
        <table class="table table-bordered" bordercolor="white" style="color:white">
            <thead>
                <tr>
                    <th class="text-center" scope="col" style="width: 75%">Comments</th>
                    <th class="text-center" scope="col">Sentiments</th>
                </tr>
            </thead>
    
            <tbody>
		      {% for review, status in reviews.items() if not reviews.hidden %}
		      <tr style="background-color:#e5091485;">
              	  <td>{{review}}</td>
	              <td><center>
	                  {{status}} : 
	                  {% if status =='Good' %}
	                    &#128515;
	                  {% else %}
	                    &#128534;
	                  {% endif %}
	                </center>
	              </td>
          		</tr>
      			{% endfor %}
    		</tbody>
 		 </table>
    </div>
    {% else %}
    <div style="color:white;">
      <h1 style="color:white"> This movie is not released yet. Stay tuned! </h1>
    </div>
    {% endif %}
  </center>

    <div class="slider-block">
    <button type="button" id="moveLeft" class="btn-nav">
      ᐊ
    </button>
    <div class="slider" id="mySlider">
        {% for item in movie_cards if not movie_cards.hidden %}
      <div class="film" id="movie0" title="{{item[1]}}" onclick="recommendcard(this)">
        <img alt="{{item[1]}} - poster" src={{item[0]}}>
        <div class="description">
          <div class="description__buttons-container">
            <div class="description__button"><i class="fas fa-plus"></i></div>
            <div class="description__button"><i class="fas fa-thumbs-up"></i></div>
            <div class="description__button"><i class="fas fa-thumbs-down"></i></div>
          </div>
          <div class="description__text-container">
            <span class="description__rating">item[2]</span>
            <span class="description__length">item[3]</span>
            <br><br>
            <span>item[3][0]</span>
            <span>&middot;</span>
            <span>item[3][1]</span>
            <span>&middot;</span>
            <span>item[3][2]</span>
          </div>
        </div>
      </div>
        {% endfor %}
    </div>
    <button type="button" id="moveRight" class="btn-nav">
      ᐅ
    </button>
  </div>
  <script src="{{ url_for('static', filename='js/slider.js') }}"></script>
  <script type="text/javascript" src="{{url_for('static', filename='recommend.js')}}"></script>

</body>
{% endblock %}

src/templates/result.html
{% extends 'base.html' %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/recommend.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/slider.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/review_slider.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
	<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/css/swiper.min.css'>
{% endblock %}
{% block title %}
{{title}}
{% endblock %}
{% block content %}
<body id="content">
<div class="movie_desc">
    	<div class="results">
	    <center>
	      <h2 id="name" class="text-uppercase">{{title}}</h2>
	    </center>
	</div>
	<br>
    <div class="mcontent">
      <div class="poster-lg">
        <img class="poster" src={{poster}}>
      </div>
      <div class="poster-sm text-center">
        <img class="poster" src={{poster}}>
      </div>
      <div id="details">
        <br/>
        <h6 id="title">TITLE: {{title}}</h6>
        <h6 id="overview">OVERVIEW: <br/>{{overview}}</h6>
        <h6 id="vote_average">RATING: {{vote_average}}/10 ({{vote_count}} votes)</h6>
        <h6 id="genres">GENRE: {{'  '.join(genres)}}</h6>
        <h6 id="date">RELEASE DATE: {{release_date}}</h6>
        <h6 id="runtime">RUNTIME: {{runtime}}</h6>
        <h6 id="status">STATUS: {{status}}</h6>
      </div>
    </div>
</div>
<br/>







{% for name, details in cast_details.items() if cast_details and not cast_details.hidden  %}
  <div class="modal fade" id="{{details[0]}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel3" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header" style="background-color: #e50914;color: white;">
          <h5 class="modal-title" id="exampleModalLabel3">{{name}}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true" style="color: white">&times;</span>
          </button>
        </div>

        <div class="modal-body">
          <img class="profile-pic" src="{{details[1]}}" alt="{{name}} - profile" style="width: 250px;height:400px;border-radius: 10px;" />
          <div style="margin-left: 20px">
            <p><strong>Birthday:</strong> {{details[2]}} </p>
            <p><strong>Place of Birth:</strong> {{details[3]}} </p>
            <p>
              <p><strong>Biography:</strong><p>
              {{details[4]}}
            </p>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
{% endfor %}


{% if casts and casts|length > 1 %}
  <div class="movie-content">
        {% for name, details in casts.items() if not casts.hidden %}

          <div class="castcard card" title="Click to know more about {{name}}" data-toggle="modal" data-target="#{{details[0]}}">
            <div class="imghvr">
              <img class="card-img-top cast-img" id="{{details[0]}}" height="360" width="240" src="{{details[2]}}" alt="{{name}} - profile">
              <figcaption class="fig">
                <button class="card-btn btn btn-danger"> Know More </button>
              </figcaption>
            </div>
            <div class="card-body">
              <p class="card-title">{{name|title}}</p>
              <p class="card-title character"><span>Character: {{details[1]|title}}</span></p>
            </div>
          </div>

      {% endfor %}
    </div>
{% endif %}



{%if reviews.items() and reviews.items()|length > 1%}
<div class="wrapper">
  <div class="content">

    <div class="product-img">
      <div class="product-img__item" id="positive">
        <img src="../static/img/positive.png" alt="positive" class="product-img__img">
      </div>
      <div class="product-img__item" id="negative">
        <img src="../static/img/negative.png" alt="negative" class="product-img__img">
      </div>
    </div>


		<div class="product-slider">
		  <button class="prev disabled">
			<span class="icon">
			  <svg class="icon icon-arrow-right"><use xlink:href="#icon-arrow-left"></use></svg>
			</span>
		  </button>
		  <button class="next">
			<span class="icon">
			  <svg class="icon icon-arrow-right"><use xlink:href="#icon-arrow-right"></use></svg>
			</span>
		  </button>
			<div class="product-slider__wrp swiper-wrapper">
			    {% for review, status in reviews.items() if not reviews.hidden %}
					<div class="product-slider__item swiper-slide" data-target={{status}}>
					  <div class="product-slider__card">
						<img src="https://res.cloudinary.com/muhammederdem/image/upload/v1536405223/starwars/item-4-bg.jpg" alt="star wars" class="product-slider__cover">
						<div class="product-slider__content">
						  <h1 class="product-slider__title">{{review}}</h1>
						</div>
					  </div>
					</div>
			    {% endfor %}
			</div>
		</div>
	</div>
</div>
{% endif %}

<svg class="hidden" hidden>
  <symbol id="icon-arrow-left" viewBox="0 0 32 32">
    <path d="M0.704 17.696l9.856 9.856c0.896 0.896 2.432 0.896 3.328 0s0.896-2.432 0-3.328l-5.792-5.856h21.568c1.312 0 2.368-1.056 2.368-2.368s-1.056-2.368-2.368-2.368h-21.568l5.824-5.824c0.896-0.896 0.896-2.432 0-3.328-0.48-0.48-1.088-0.704-1.696-0.704s-1.216 0.224-1.696 0.704l-9.824 9.824c-0.448 0.448-0.704 1.056-0.704 1.696s0.224 1.248 0.704 1.696z"></path>
  </symbol>
  <symbol id="icon-arrow-right" viewBox="0 0 32 32">
    <path d="M31.296 14.336l-9.888-9.888c-0.896-0.896-2.432-0.896-3.328 0s-0.896 2.432 0 3.328l5.824 5.856h-21.536c-1.312 0-2.368 1.056-2.368 2.368s1.056 2.368 2.368 2.368h21.568l-5.856 5.824c-0.896 0.896-0.896 2.432 0 3.328 0.48 0.48 1.088 0.704 1.696 0.704s1.216-0.224 1.696-0.704l9.824-9.824c0.448-0.448 0.704-1.056 0.704-1.696s-0.224-1.248-0.704-1.664z"></path>
  </symbol>
</svg>

    <center>
    <h2 class="rec-name">Recommended for you</h2>
    </center>
      <div class="slider-block">
      <button type="button" id="moveLeft" class="btn-nav">
        ᐊ
      </button>
      <div class="slider" id="mySlider">
          {% for title, poster, popularity, genres, rating, id in movie_cards if not movie_cards.hidden %}
        <div class="film" id="movie0" title="{{title}}">
            <a href="{{url_for('.result', page_state='movie', title=title)}}">
            <img alt="{{details}} - poster" src={{poster}}>
            </a>
            <div class="description">
            <div class="description__buttons-container">
              <div data-id="{{id}}" class="description__button add-to-watch-list">
                  <i class="fas fa-plus"></i>
              </div>
<!--              <div class="description__button">-->
<!--                  <i class="fas fa-thumbs-up"></i>-->
<!--              </div>-->
<!--              <div class="description__button">-->
<!--                  <i class="fas fa-thumbs-down"></i>-->
<!--              </div>-->
            </div>
            <div class="description__text-container">
              <span class="description__rating">{{rating}}</span>
              <span class="description__popularity">{{popularity}}%</span>
              <br><br>
              {% for genre in genres %}
              <span>{{genre}}  </span>
              {% endfor %}
            </div>
          </div>
        </div>
          {% endfor %}
      </div>
      <button type="button" id="moveRight" class="btn-nav">
        ᐅ
      </button>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://unpkg.com/swiper/swiper-bundle.js"></script>
    <script src="{{ url_for('static', filename='js/slider.js') }}"></script>
    <script src="{{ url_for('static', filename='js/addToWatchlist.js') }}"></script>
</body>
{% endblock %}